language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.8

script:
  - echo 'credentials += Credentials("Artifactory Realm", "drivergrp.jfrog.io", "sbt-publisher", sys.env("ARTIFACTORY_PASSWORD"))' > project/credentials.sbt "sbt clean test"
